version: "3.3"
services:
  supertuxkart-server:
    image: iluvatyr/supertuxkart:normal-1.4
    container_name: supertuxkart-server
    restart: unless-stopped
    volumes:
      - ./stk/assets/:/usr/local/share/supertuxkart/data/ # needed STK ASSETS
      #- ./stk/server_config.xml:/stk/server_config.xml # needed to customize your server
      #- ./stk/motd.txt:/stk/motd.txt # optional, but recommended message of the day
      #- ./stk/addons/:/home/supertuxkart/.local/share/supertuxkart/addons/ # optional but recommended addon tracks
      #- ./stk/stkservers.db:/stk/stkservers.db # optional but recommended, has to be added in server_config.xml
      #- ./stk/replay/:/home/supertuxkart/.local/share/supertuxkart/replay/ #optional
      #- ./stk/grandprix/:/home/supertuxkart/.local/share/supertuxkart/grandprix/ #optional
      #- ./stk/screenshots:/home/supertuxkart/.local/share/supertuxkart/screenshots/ #optional
      #- ./stk/logs/stdout.log:/home/supertuxkart/.config/supertuxkart/config-0.10/stdout.log # optional logs mounted on docker host, stdout.log has to preexist on host
      #- ./stk/logs/server_config.log:/home/supertuxkart/.config/supertuxkart/config-0.10/server_config.log # server_config.log has to preexist on host
    environment:
      #- TZ=Europe/Berlin # (default UTC)
      #- PUID=1358 # (default 1337)
      #- PGID=1358 # (default 1337)
      #- UPTIME_PUSH_URL=https://your-push-url.yourdomain.com/ # (default unset)
      #- UPTIME_PUSH_PERIOD=300 # (default 60)
      - STK_USERNAME=your-stk-username # (needed:default unset, register on https://online.supertuxkart.net )
      - STK_PASSWORD=your_password # (needed:default unset)
      #- STK_PORT=2762 # (default 2759, match this with port set and firewallsetting)
      #- STK_SERVER_CONF=my_server_config.xml # (default server_config.xml --> referring on how mounted inside container)
      #- STK_AI_KARTS=3 # (default 0)
      #- STK_FIREWALLED=true # (default false)
      #- STK_INSTALL_ADDONS=true # (default false)
    ports:
      - "2759:2759/udp"
